/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import javax.swing.JFrame;


/**
 *
 * @author Bendenia M'hamed
 */
public class Acceuil extends javax.swing.JFrame {
    private static final long serialVersionUID = 1;
    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        sortit = new javax.swing.JButton();
        Min = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        apropos = new javax.swing.JLabel();
        AdminB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(54, 34, 29));
        jLabel3.setText(" X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 20, -1));

        sortit.setBackground(new java.awt.Color(54, 34, 29));
        sortit.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        sortit.setForeground(new java.awt.Color(255, 255, 255));
        sortit.setText("Sortir ");
        sortit.setBorder(null);
        sortit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sortit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortitActionPerformed(evt);
            }
        });
        getContentPane().add(sortit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 350, 50));

        Min.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Min.setForeground(new java.awt.Color(255, 255, 255));
        Min.setText("_");
        Min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinMouseClicked(evt);
            }
        });
        getContentPane().add(Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 20, 30));

        Close.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Close.setForeground(new java.awt.Color(255, 255, 255));
        Close.setText(" X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, 20));

        apropos.setFont(new java.awt.Font("Calibri Light", 3, 20)); // NOI18N
        apropos.setForeground(new java.awt.Color(255, 255, 255));
        apropos.setText("A propos");
        apropos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apropos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aproposMouseClicked(evt);
            }
        });
        getContentPane().add(apropos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        AdminB.setBackground(new java.awt.Color(54, 34, 29));
        AdminB.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        AdminB.setForeground(new java.awt.Color(255, 255, 255));
        AdminB.setText("Se connecter");
        AdminB.setBorder(null);
        AdminB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminBMouseClicked(evt);
            }
        });
        AdminB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBActionPerformed(evt);
            }
        });
        getContentPane().add(AdminB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 350, 50));

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Residence manager");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icones/0_NrTRUiI3029OzdJL.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
      System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseClicked
        
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinMouseClicked

    private void aproposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aproposMouseClicked
        A_propos a_propos=new A_propos();
        a_propos.setVisible(true);
    }//GEN-LAST:event_aproposMouseClicked

    private void AdminBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminBMouseClicked
        
        Connexion connexion=new Connexion();
        connexion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AdminBMouseClicked

    private void AdminBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminBActionPerformed

    private void sortitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortitActionPerformed
       
        System.exit(0);
    }//GEN-LAST:event_sortitActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminB;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Min;
    private javax.swing.JLabel apropos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton sortit;
    // End of variables declaration//GEN-END:variables
}
