/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import app.connect;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Bendenia M'hamed
 */
public class Document extends javax.swing.JFrame {
    private static final long serialVersionUID = 1;
    Statement statement;
    ResultSet result;
   connect maConnexion=new connect();
   DefaultTableModel model=new DefaultTableModel();
     



    /**
     * Creates new form Document
     */
    public Document() {
        initComponents();
        this.setLocationRelativeTo(null);
         model.addColumn("numerochambre");
         model.addColumn("numbloc");
         model.addColumn("autre");
        
          try{
            String sql="Select * from document1";
            statement=maConnexion.obtenirconnexion().createStatement();
            result= statement.executeQuery(sql);
            while(result.next()){
                model.addRow(new Object[]{result.getString("numchambre"),result.getString("numbloc"),result.getString("autre")});
            }
    }catch(Exception ex){
        System.err.println(ex);
    }
        table.setModel(model);
                                                                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        cote = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        resume = new javax.swing.JLabel();
        numerobloctxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ajouter = new javax.swing.JButton();
        Close = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        autretxt = new javax.swing.JTextArea();
        supprimer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        modifier = new javax.swing.JButton();
        Min = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        numerochambretxt = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        cote.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        cote.setText("Numéro : *");

        titre.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        titre.setText("Pavillon : *");

        resume.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        resume.setText("Autre :");

        numerobloctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerobloctxtActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icones/icons8-dossier-de-documents-64.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icones/icons8-lecture-16.png"))); // NOI18N
        jLabel12.setText("Chambre");

        ajouter.setBackground(new java.awt.Color(0, 153, 102));
        ajouter.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icones/icons8-plus-24.png"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        Close.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        Close.setText(" X");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        autretxt.setColumns(100);
        autretxt.setRows(10);
        jScrollPane1.setViewportView(autretxt);

        supprimer.setBackground(new java.awt.Color(255, 102, 51));
        supprimer.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 255, 255));
        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icones/icons8-trash-can-26.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        modifier.setBackground(new java.awt.Color(102, 204, 255));
        modifier.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        modifier.setForeground(new java.awt.Color(255, 255, 255));
        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icones/icons8-réglages-horizontal-24.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        Min.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Min.setText("_");
        Min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinMouseClicked(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titre)
                    .addComponent(cote)
                    .addComponent(resume))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numerochambretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numerobloctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Min)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Close)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cote, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numerochambretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numerobloctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titre)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Min, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resume)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void deplace(int i){
        try{
            numerochambretxt.setText(model.getValueAt(i,0).toString());
            numerobloctxt.setText(model.getValueAt(i,1).toString());
            autretxt.setText(model.getValueAt(i,2).toString()); 
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "erreur de déplacement "+e.getLocalizedMessage());
        }
    }
   public void actualiser(){
        try{
            model.setRowCount(0);
            statement=maConnexion.obtenirconnexion().createStatement();
            result= statement.executeQuery("select * from document1");
             while(result.next()){
                model.addRow(new Object[]{result.getString("numchambre"),result.getString("numbloc"),result.getString("autre")});
        }}catch(Exception e){
            System.err.println(e);
            table.setModel(model);
        }
        
    }
    private void numerobloctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerobloctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerobloctxtActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
    if(JOptionPane.showConfirmDialog(null,"Etes vous sûr de vouloir supprimer une chambre ?",
                "Supprimer chambre",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){ 
        try{  
            if(numerochambretxt.getText().length() !=0)
                statement.executeUpdate("Delete from Document1 where numchambre ="+numerochambretxt.getText());
            else 
                JOptionPane.showMessageDialog(null, "Remplire le champ Numero SVP !");
            }    
     
      
      catch(Exception e){
                JOptionPane.showInternalMessageDialog(null,"Erreur de suppréssion "+e.getMessage());
            }
    }
      
        // Pour vider les champs
        numerochambretxt.setText(null);   
        numerobloctxt.setText(null);
        autretxt.setText(null);
        actualiser();
    }//GEN-LAST:event_supprimerActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
        try{
              int i =table.getSelectedRow();
           deplace(i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur de déplacement"+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        String numerochambre=numerochambretxt.getText().toString();
        String numbloc=numerobloctxt.getText().toString();
        String autre=autretxt.getText().toString();
        String requete="insert into document1(numchambre,numbloc,autre)VALUES('"+numerochambre+"','"+numbloc+"','"+autre+"')";

        try{
            if(numerochambre.equals("")||numbloc.equals("")){
               
            JOptionPane.showMessageDialog(null,"Veuillez vérifier vos données svp !");
            if(numerochambre.equals("")){
                numerochambretxt.setBackground(Color.red);
            }
            if(numbloc.equals(""))   
                 numerobloctxt.setBackground(Color.red);
            }else{
            statement.executeUpdate(requete);
            actualiser();
            Sauvegarde sauvegarde =new Sauvegarde();
            sauvegarde.setVisible(true);
   
                
            // Pour vider les champs
        numerochambretxt.setText(null);   
        numerobloctxt.setText(null);
        autretxt.setText(null);
        numerochambretxt.setBackground(Color.white);
        numerobloctxt.setBackground(Color.white);

            actualiser();
            }
        }  catch(Exception ex){
        
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }

        

    }//GEN-LAST:event_ajouterActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Etes vous sûr de vouloir modifier ?",
               "Modifier",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
         try{
        
        
        // les val oranges sont les val de la BD
        
        statement.executeUpdate("UPDATE document1 SET numbloc='"+numerobloctxt.getText()+"',autre='"+autretxt.getText()+"'where numchambre='"+numerochambretxt.getText()+"'");
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Erreur de modification "+e.getMessage());
                System.err.println(e);
            }
        }
          actualiser();
            // Pour vider les champs
        numerochambretxt.setText(null);   
        numerobloctxt.setText(null);
        autretxt.setText(null);
    }//GEN-LAST:event_modifierActionPerformed

    private void MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinMouseClicked
        
         this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Document.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Document().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Min;
    private javax.swing.JButton ajouter;
    private javax.swing.JTextArea autretxt;
    private javax.swing.JLabel cote;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField numerobloctxt;
    private javax.swing.JTextField numerochambretxt;
    private javax.swing.JLabel resume;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable table;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
